version: "3.8"

services:
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=users
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - 2908:5432
  users:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

volumes:
  pgdata:
 